# Generated by Django 5.2.13 on 2026-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress_latitude_useraddress_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
