# Generated by Django 5.2.13 on 2026-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0002_alter_city_options_alter_country_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_new_users_discount_email", models.BooleanField(default=True)),
                (
                    "new_users_discount_percentage",
                    models.PositiveIntegerField(blank=True, default=10, null=True),
                ),
                (
                    "new_users_fixed_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
