# Generated by Django 5.2.13 on 2026-04-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="used",
        ),
        migrations.AddField(
            model_name="discount",
            name="current_uses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discount",
            name="max_uses",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="discount",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
