# Generated by Django 5.2.13 on 2026-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_discount_used_discount_current_uses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="fixed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
