# Generated by Django 5.2.13 on 2026-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_discount_code_alter_discount_fixed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="exp",
            new_name="expiration",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="amount",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="library",
        ),
        migrations.AddField(
            model_name="order",
            name="book_store_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
