# Generated by Django 5.2.13 on 2026-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_rename_exp_discount_expiration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
